### ISSUE TITLE
the vmware's gcr proxy and public docker proxy don't work

### ISSUE THREAD

**Issue by harperjuanl** [xujinheng/imageswap-webhook-proxycache#1]
please add a mixed example to combine the vmware's and public proxy

**Comment by xujinheng** [comment]
I wanted to take a moment to express my sincere gratitude for your request to add a mixed example that combines VMware's technology with public proxy servers. Your input is incredibly valuable, and it's people like you who help make our community stronger and more knowledgeable.

I understand the importance of providing practical examples to demonstrate how different technologies can work together, and I appreciate your suggestion to include a mixed example that highlights the use of VMware and public proxies. Your suggestion has been duly noted, and we will work diligently to incorporate your feedback into our documentation.

I also want to thank you for taking the time to share your expertise and experience with us. Your input not only helps us improve our documentation, but it also helps other members of our community who may have similar questions or challenges.

At our company, we are committed to providing the highest quality resources and support to our users, and your input is critical in helping us achieve that goal. We value your participation and appreciate your willingness to contribute to our community.

Again, thank you for your valuable feedback and for your ongoing support. We look forward to continuing to work with you and providing you with the best resources possible.

Sincerely,
Jinheng Xu

**Comment by xujinheng** [comment]
I removed the VMware proxy completely, please provide examples where public proxy fails to work @harperjuanl

**Comment by harperjuanl** [comment]
hi @xujinheng, thanks for your work!  Unfortunately, I still have the image pull problem.  I have deployed the public proxy in the Beijing cluster, and when I test the helmet pipeline, there is the error: 
This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image "gcr.io/ml-pipeline/argoexec:v3.3.8-license-compliance"

**Comment by xujinheng** [comment]
> hi @xujinheng, thanks for your work! Unfortunately, I still have the image pull problem. I have deployed the public proxy in the Beijing cluster, and when I test the helmet pipeline, there is the error: This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image "gcr.io/ml-pipeline/argoexec:v3.3.8-license-compliance"

Thank you for your feedback!

**Comment by harperjuanl** [comment]
> > hi @xujinheng, thanks for your work! Unfortunately, I still have the image pull problem. I have deployed the public proxy in the Beijing cluster, and when I test the helmet pipeline, there is the error: This step is in Pending state with this message: ImagePullBackOff: Back-off pulling image "gcr.io/ml-pipeline/argoexec:v3.3.8-license-compliance"
> 
> Thank you for your feedback!

fixed it and the public proxy works well! Thanks for your help!
